
import { languages } from 'monaco-editor';
import solidjsUsePackageJson from '/node_modules/solidjs-use/package.json?raw';

import solidjs1Types from '/node_modules/solidjs-use/dist/index.d.ts?raw';
import solidjs2Types from '/node_modules/solidjs-use/dist/solid-to-vue.d.ts?raw';
import solidjs3Types from '/node_modules/solidjs-use/dist/ssr-handlers.d.ts?raw';
import solidjs4Types from '/node_modules/solidjs-use/dist/types.d.ts?raw';
import solidjs5Types from '/node_modules/solidjs-use/dist/_configurable.d.ts?raw';
import solidjs6Types from '/node_modules/solidjs-use/dist/createAsyncMemo/index.d.ts?raw';
import solidjs7Types from '/node_modules/solidjs-use/dist/createUnAccessorFn/index.d.ts?raw';
import solidjs8Types from '/node_modules/solidjs-use/dist/onClickOutside/index.d.ts?raw';
import solidjs9Types from '/node_modules/solidjs-use/dist/onKeyStroke/index.d.ts?raw';
import solidjs10Types from '/node_modules/solidjs-use/dist/onLongPress/index.d.ts?raw';
import solidjs11Types from '/node_modules/solidjs-use/dist/onStartTyping/index.d.ts?raw';
import solidjs12Types from '/node_modules/solidjs-use/dist/useActiveElement/index.d.ts?raw';
import solidjs13Types from '/node_modules/solidjs-use/dist/useAsyncState/index.d.ts?raw';
import solidjs14Types from '/node_modules/solidjs-use/dist/useBase64/index.d.ts?raw';
import solidjs15Types from '/node_modules/solidjs-use/dist/useBase64/serialization.d.ts?raw';
import solidjs16Types from '/node_modules/solidjs-use/dist/useBattery/index.d.ts?raw';
import solidjs17Types from '/node_modules/solidjs-use/dist/useBluetooth/index.d.ts?raw';
import solidjs18Types from '/node_modules/solidjs-use/dist/useBreakpoints/breakpoints.d.ts?raw';
import solidjs19Types from '/node_modules/solidjs-use/dist/useBreakpoints/index.d.ts?raw';
import solidjs20Types from '/node_modules/solidjs-use/dist/useBroadcastChannel/index.d.ts?raw';
import solidjs21Types from '/node_modules/solidjs-use/dist/useBrowserLocation/component.d.ts?raw';
import solidjs22Types from '/node_modules/solidjs-use/dist/useBrowserLocation/index.d.ts?raw';
import solidjs23Types from '/node_modules/solidjs-use/dist/useClipboard/index.d.ts?raw';
import solidjs24Types from '/node_modules/solidjs-use/dist/useCloned/index.d.ts?raw';
import solidjs25Types from '/node_modules/solidjs-use/dist/useColorMode/index.d.ts?raw';
import solidjs26Types from '/node_modules/solidjs-use/dist/useConfirmDialog/index.d.ts?raw';
import solidjs27Types from '/node_modules/solidjs-use/dist/useCssTransition/index.d.ts?raw';
import solidjs28Types from '/node_modules/solidjs-use/dist/useCssVar/index.d.ts?raw';
import solidjs29Types from '/node_modules/solidjs-use/dist/useCycleList/index.d.ts?raw';
import solidjs30Types from '/node_modules/solidjs-use/dist/useDark/index.d.ts?raw';
import solidjs31Types from '/node_modules/solidjs-use/dist/useDebouncedHistoryTravel/index.d.ts?raw';
import solidjs32Types from '/node_modules/solidjs-use/dist/useDeviceMotion/index.d.ts?raw';
import solidjs33Types from '/node_modules/solidjs-use/dist/useDeviceOrientation/index.d.ts?raw';
import solidjs34Types from '/node_modules/solidjs-use/dist/useDevicePixelRatio/index.d.ts?raw';
import solidjs35Types from '/node_modules/solidjs-use/dist/useDevicesList/index.d.ts?raw';
import solidjs36Types from '/node_modules/solidjs-use/dist/useDisplayMedia/index.d.ts?raw';
import solidjs37Types from '/node_modules/solidjs-use/dist/useDocumentVisibility/index.d.ts?raw';
import solidjs38Types from '/node_modules/solidjs-use/dist/useDraggable/index.d.ts?raw';
import solidjs39Types from '/node_modules/solidjs-use/dist/useDropZone/index.d.ts?raw';
import solidjs40Types from '/node_modules/solidjs-use/dist/useElementBounding/index.d.ts?raw';
import solidjs41Types from '/node_modules/solidjs-use/dist/useElementByPoint/index.d.ts?raw';
import solidjs42Types from '/node_modules/solidjs-use/dist/useElementHover/index.d.ts?raw';
import solidjs43Types from '/node_modules/solidjs-use/dist/useElementSize/index.d.ts?raw';
import solidjs44Types from '/node_modules/solidjs-use/dist/useElementVisibility/index.d.ts?raw';
import solidjs45Types from '/node_modules/solidjs-use/dist/useEventBus/index.d.ts?raw';
import solidjs46Types from '/node_modules/solidjs-use/dist/useEventBus/internal.d.ts?raw';
import solidjs47Types from '/node_modules/solidjs-use/dist/useEventListener/index.d.ts?raw';
import solidjs48Types from '/node_modules/solidjs-use/dist/useEventSource/index.d.ts?raw';
import solidjs49Types from '/node_modules/solidjs-use/dist/useEyeDropper/index.d.ts?raw';
import solidjs50Types from '/node_modules/solidjs-use/dist/useFavicon/index.d.ts?raw';
import solidjs51Types from '/node_modules/solidjs-use/dist/useFetch/index.d.ts?raw';
import solidjs52Types from '/node_modules/solidjs-use/dist/useFileDialog/index.d.ts?raw';
import solidjs53Types from '/node_modules/solidjs-use/dist/useFileSystemAccess/index.d.ts?raw';
import solidjs54Types from '/node_modules/solidjs-use/dist/useFocus/index.d.ts?raw';
import solidjs55Types from '/node_modules/solidjs-use/dist/useFocusWithin/index.d.ts?raw';
import solidjs56Types from '/node_modules/solidjs-use/dist/useFps/index.d.ts?raw';
import solidjs57Types from '/node_modules/solidjs-use/dist/useFullscreen/index.d.ts?raw';
import solidjs58Types from '/node_modules/solidjs-use/dist/useGamepad/index.d.ts?raw';
import solidjs59Types from '/node_modules/solidjs-use/dist/useGeolocation/index.d.ts?raw';
import solidjs60Types from '/node_modules/solidjs-use/dist/useHistoryTravel/index.d.ts?raw';
import solidjs61Types from '/node_modules/solidjs-use/dist/useIdle/index.d.ts?raw';
import solidjs62Types from '/node_modules/solidjs-use/dist/useImage/index.d.ts?raw';
import solidjs63Types from '/node_modules/solidjs-use/dist/useInfiniteScroll/index.d.ts?raw';
import solidjs64Types from '/node_modules/solidjs-use/dist/useIntersectionObserver/index.d.ts?raw';
import solidjs65Types from '/node_modules/solidjs-use/dist/useKeyModifier/index.d.ts?raw';
import solidjs66Types from '/node_modules/solidjs-use/dist/useLocalStorage/index.d.ts?raw';
import solidjs67Types from '/node_modules/solidjs-use/dist/useMagicKeys/aliasMap.d.ts?raw';
import solidjs68Types from '/node_modules/solidjs-use/dist/useMagicKeys/index.d.ts?raw';
import solidjs69Types from '/node_modules/solidjs-use/dist/useManualHistoryTravel/index.d.ts?raw';
import solidjs70Types from '/node_modules/solidjs-use/dist/useMediaControls/index.d.ts?raw';
import solidjs71Types from '/node_modules/solidjs-use/dist/useMediaQuery/index.d.ts?raw';
import solidjs72Types from '/node_modules/solidjs-use/dist/useMemoize/index.d.ts?raw';
import solidjs73Types from '/node_modules/solidjs-use/dist/useMemory/index.d.ts?raw';
import solidjs74Types from '/node_modules/solidjs-use/dist/useMounted/index.d.ts?raw';
import solidjs75Types from '/node_modules/solidjs-use/dist/useMouse/index.d.ts?raw';
import solidjs76Types from '/node_modules/solidjs-use/dist/useMouseInElement/index.d.ts?raw';
import solidjs77Types from '/node_modules/solidjs-use/dist/useMousePressed/index.d.ts?raw';
import solidjs78Types from '/node_modules/solidjs-use/dist/useMutationObserver/index.d.ts?raw';
import solidjs79Types from '/node_modules/solidjs-use/dist/useNavigatorLanguage/index.d.ts?raw';
import solidjs80Types from '/node_modules/solidjs-use/dist/useNetwork/index.d.ts?raw';
import solidjs81Types from '/node_modules/solidjs-use/dist/useNow/component.d.ts?raw';
import solidjs82Types from '/node_modules/solidjs-use/dist/useNow/index.d.ts?raw';
import solidjs83Types from '/node_modules/solidjs-use/dist/useObjectUrl/component.d.ts?raw';
import solidjs84Types from '/node_modules/solidjs-use/dist/useObjectUrl/index.d.ts?raw';
import solidjs85Types from '/node_modules/solidjs-use/dist/useOffsetPagination/index.d.ts?raw';
import solidjs86Types from '/node_modules/solidjs-use/dist/useOnline/index.d.ts?raw';
import solidjs87Types from '/node_modules/solidjs-use/dist/usePageLeave/index.d.ts?raw';
import solidjs88Types from '/node_modules/solidjs-use/dist/useParallax/index.d.ts?raw';
import solidjs89Types from '/node_modules/solidjs-use/dist/usePermission/index.d.ts?raw';
import solidjs90Types from '/node_modules/solidjs-use/dist/usePointer/index.d.ts?raw';
import solidjs91Types from '/node_modules/solidjs-use/dist/usePointerSwipe/index.d.ts?raw';
import solidjs92Types from '/node_modules/solidjs-use/dist/usePreferredColorScheme/index.d.ts?raw';
import solidjs93Types from '/node_modules/solidjs-use/dist/usePreferredContrast/index.d.ts?raw';
import solidjs94Types from '/node_modules/solidjs-use/dist/usePreferredDark/component.d.ts?raw';
import solidjs95Types from '/node_modules/solidjs-use/dist/usePreferredDark/index.d.ts?raw';
import solidjs96Types from '/node_modules/solidjs-use/dist/usePreferredLanguages/index.d.ts?raw';
import solidjs97Types from '/node_modules/solidjs-use/dist/usePreferredReducedMotion/index.d.ts?raw';
import solidjs98Types from '/node_modules/solidjs-use/dist/useRafFn/index.d.ts?raw';
import solidjs99Types from '/node_modules/solidjs-use/dist/useResizeObserver/index.d.ts?raw';
import solidjs100Types from '/node_modules/solidjs-use/dist/useScreenOrientation/index.d.ts?raw';
import solidjs101Types from '/node_modules/solidjs-use/dist/useScreenSafeArea/index.d.ts?raw';
import solidjs102Types from '/node_modules/solidjs-use/dist/useScriptTag/index.d.ts?raw';
import solidjs103Types from '/node_modules/solidjs-use/dist/useScroll/index.d.ts?raw';
import solidjs104Types from '/node_modules/solidjs-use/dist/useScrollLock/index.d.ts?raw';
import solidjs105Types from '/node_modules/solidjs-use/dist/useSessionStorage/index.d.ts?raw';
import solidjs106Types from '/node_modules/solidjs-use/dist/useShare/index.d.ts?raw';
import solidjs107Types from '/node_modules/solidjs-use/dist/useSpeechRecognition/index.d.ts?raw';
import solidjs108Types from '/node_modules/solidjs-use/dist/useSpeechRecognition/types.d.ts?raw';
import solidjs109Types from '/node_modules/solidjs-use/dist/useSpeechSynthesis/index.d.ts?raw';
import solidjs110Types from '/node_modules/solidjs-use/dist/useStepper/index.d.ts?raw';
import solidjs111Types from '/node_modules/solidjs-use/dist/useStorage/guess.d.ts?raw';
import solidjs112Types from '/node_modules/solidjs-use/dist/useStorage/index.d.ts?raw';
import solidjs113Types from '/node_modules/solidjs-use/dist/useStorageAsync/index.d.ts?raw';
import solidjs114Types from '/node_modules/solidjs-use/dist/useStyleTag/index.d.ts?raw';
import solidjs115Types from '/node_modules/solidjs-use/dist/useSupported/index.d.ts?raw';
import solidjs116Types from '/node_modules/solidjs-use/dist/useSwipe/index.d.ts?raw';
import solidjs117Types from '/node_modules/solidjs-use/dist/useTextareaAutoSize/index.d.ts?raw';
import solidjs118Types from '/node_modules/solidjs-use/dist/useTextDirection/index.d.ts?raw';
import solidjs119Types from '/node_modules/solidjs-use/dist/useTextSelection/index.d.ts?raw';
import solidjs120Types from '/node_modules/solidjs-use/dist/useThrottledHistoryTravel/index.d.ts?raw';
import solidjs121Types from '/node_modules/solidjs-use/dist/useTimeAgo/component.d.ts?raw';
import solidjs122Types from '/node_modules/solidjs-use/dist/useTimeAgo/index.d.ts?raw';
import solidjs123Types from '/node_modules/solidjs-use/dist/useTimestamp/index.d.ts?raw';
import solidjs124Types from '/node_modules/solidjs-use/dist/useTitle/index.d.ts?raw';
import solidjs125Types from '/node_modules/solidjs-use/dist/useUrlSearchParams/index.d.ts?raw';
import solidjs126Types from '/node_modules/solidjs-use/dist/useUserMedia/index.d.ts?raw';
import solidjs127Types from '/node_modules/solidjs-use/dist/useVibrate/index.d.ts?raw';
import solidjs128Types from '/node_modules/solidjs-use/dist/useVirtualList/index.d.ts?raw';
import solidjs129Types from '/node_modules/solidjs-use/dist/useWakeLock/index.d.ts?raw';
import solidjs130Types from '/node_modules/solidjs-use/dist/useWebNotification/index.d.ts?raw';
import solidjs131Types from '/node_modules/solidjs-use/dist/useWebSocket/index.d.ts?raw';
import solidjs132Types from '/node_modules/solidjs-use/dist/useWebWorker/index.d.ts?raw';
import solidjs133Types from '/node_modules/solidjs-use/dist/useWebWorkerFn/index.d.ts?raw';
import solidjs134Types from '/node_modules/solidjs-use/dist/useWindowFocus/index.d.ts?raw';
import solidjs135Types from '/node_modules/solidjs-use/dist/useWindowScroll/index.d.ts?raw';
import solidjs136Types from '/node_modules/solidjs-use/dist/useWindowSize/index.d.ts?raw';
import solidjs137Types from '/node_modules/solidjs-use/dist/useWebWorkerFn/lib/createWorkerBlobUrl.d.ts?raw';
import solidjs138Types from '/node_modules/solidjs-use/dist/useWebWorkerFn/lib/depsParser.d.ts?raw';
import solidjs139Types from '/node_modules/solidjs-use/dist/useWebWorkerFn/lib/jobRunner.d.ts?raw';
import solidjs140Types from '/node_modules/solidjs-use/dist/node_modules/@solidjs-use/shared/index.d.ts?raw';
import solidjs141Types from '/node_modules/solidjs-use/dist/node_modules/@solidjs-use/shared/solid-to-vue.d.ts?raw';
import solidjs142Types from '/node_modules/solidjs-use/dist/node_modules/@solidjs-use/shared/accessorDebounced/index.d.ts?raw';
import solidjs143Types from '/node_modules/solidjs-use/dist/node_modules/@solidjs-use/shared/accessorDefault/index.d.ts?raw';
import solidjs144Types from '/node_modules/solidjs-use/dist/node_modules/@solidjs-use/shared/accessorThrottled/index.d.ts?raw';
import solidjs145Types from '/node_modules/solidjs-use/dist/node_modules/@solidjs-use/shared/createEventHook/index.d.ts?raw';
import solidjs146Types from '/node_modules/solidjs-use/dist/node_modules/@solidjs-use/shared/createSharedComposable/index.d.ts?raw';
import solidjs147Types from '/node_modules/solidjs-use/dist/node_modules/@solidjs-use/shared/get/index.d.ts?raw';
import solidjs148Types from '/node_modules/solidjs-use/dist/node_modules/@solidjs-use/shared/isDefined/index.d.ts?raw';
import solidjs149Types from '/node_modules/solidjs-use/dist/node_modules/@solidjs-use/shared/makeDestructurable/index.d.ts?raw';
import solidjs150Types from '/node_modules/solidjs-use/dist/node_modules/@solidjs-use/shared/mutableMemo/index.d.ts?raw';
import solidjs151Types from '/node_modules/solidjs-use/dist/node_modules/@solidjs-use/shared/omitMutable/index.d.ts?raw';
import solidjs152Types from '/node_modules/solidjs-use/dist/node_modules/@solidjs-use/shared/pickMutable/index.d.ts?raw';
import solidjs153Types from '/node_modules/solidjs-use/dist/node_modules/@solidjs-use/shared/reactify/index.d.ts?raw';
import solidjs154Types from '/node_modules/solidjs-use/dist/node_modules/@solidjs-use/shared/reactifyObject/index.d.ts?raw';
import solidjs155Types from '/node_modules/solidjs-use/dist/node_modules/@solidjs-use/shared/resolveAccessor/index.d.ts?raw';
import solidjs156Types from '/node_modules/solidjs-use/dist/node_modules/@solidjs-use/shared/signalAutoReset/index.d.ts?raw';
import solidjs157Types from '/node_modules/solidjs-use/dist/node_modules/@solidjs-use/shared/syncSignal/index.d.ts?raw';
import solidjs158Types from '/node_modules/solidjs-use/dist/node_modules/@solidjs-use/shared/syncSignals/index.d.ts?raw';
import solidjs159Types from '/node_modules/solidjs-use/dist/node_modules/@solidjs-use/shared/toAccessors/index.d.ts?raw';
import solidjs160Types from '/node_modules/solidjs-use/dist/node_modules/@solidjs-use/shared/toReactive/index.d.ts?raw';
import solidjs161Types from '/node_modules/solidjs-use/dist/node_modules/@solidjs-use/shared/tryOnCleanup/index.d.ts?raw';
import solidjs162Types from '/node_modules/solidjs-use/dist/node_modules/@solidjs-use/shared/tryOnMount/index.d.ts?raw';
import solidjs163Types from '/node_modules/solidjs-use/dist/node_modules/@solidjs-use/shared/unAccessor/index.d.ts?raw';
import solidjs164Types from '/node_modules/solidjs-use/dist/node_modules/@solidjs-use/shared/until/index.d.ts?raw';
import solidjs165Types from '/node_modules/solidjs-use/dist/node_modules/@solidjs-use/shared/useArrayEvery/index.d.ts?raw';
import solidjs166Types from '/node_modules/solidjs-use/dist/node_modules/@solidjs-use/shared/useArrayFilter/index.d.ts?raw';
import solidjs167Types from '/node_modules/solidjs-use/dist/node_modules/@solidjs-use/shared/useArrayFind/index.d.ts?raw';
import solidjs168Types from '/node_modules/solidjs-use/dist/node_modules/@solidjs-use/shared/useArrayFindIndex/index.d.ts?raw';
import solidjs169Types from '/node_modules/solidjs-use/dist/node_modules/@solidjs-use/shared/useArrayJoin/index.d.ts?raw';
import solidjs170Types from '/node_modules/solidjs-use/dist/node_modules/@solidjs-use/shared/useArrayMap/index.d.ts?raw';
import solidjs171Types from '/node_modules/solidjs-use/dist/node_modules/@solidjs-use/shared/useArrayReduce/index.d.ts?raw';
import solidjs172Types from '/node_modules/solidjs-use/dist/node_modules/@solidjs-use/shared/useArraySome/index.d.ts?raw';
import solidjs173Types from '/node_modules/solidjs-use/dist/node_modules/@solidjs-use/shared/useArrayUnique/index.d.ts?raw';
import solidjs174Types from '/node_modules/solidjs-use/dist/node_modules/@solidjs-use/shared/useAsyncQueue/index.d.ts?raw';
import solidjs175Types from '/node_modules/solidjs-use/dist/node_modules/@solidjs-use/shared/useCounter/index.d.ts?raw';
import solidjs176Types from '/node_modules/solidjs-use/dist/node_modules/@solidjs-use/shared/useDateFormat/index.d.ts?raw';
import solidjs177Types from '/node_modules/solidjs-use/dist/node_modules/@solidjs-use/shared/useDebounceFn/index.d.ts?raw';
import solidjs178Types from '/node_modules/solidjs-use/dist/node_modules/@solidjs-use/shared/useInterval/index.d.ts?raw';
import solidjs179Types from '/node_modules/solidjs-use/dist/node_modules/@solidjs-use/shared/useIntervalFn/index.d.ts?raw';
import solidjs180Types from '/node_modules/solidjs-use/dist/node_modules/@solidjs-use/shared/useLastChanged/index.d.ts?raw';
import solidjs181Types from '/node_modules/solidjs-use/dist/node_modules/@solidjs-use/shared/useSorted/index.d.ts?raw';
import solidjs182Types from '/node_modules/solidjs-use/dist/node_modules/@solidjs-use/shared/useThrottleFn/index.d.ts?raw';
import solidjs183Types from '/node_modules/solidjs-use/dist/node_modules/@solidjs-use/shared/useTimeout/index.d.ts?raw';
import solidjs184Types from '/node_modules/solidjs-use/dist/node_modules/@solidjs-use/shared/useTimeoutFn/index.d.ts?raw';
import solidjs185Types from '/node_modules/solidjs-use/dist/node_modules/@solidjs-use/shared/useTimeoutPoll/index.d.ts?raw';
import solidjs186Types from '/node_modules/solidjs-use/dist/node_modules/@solidjs-use/shared/useToggle/index.d.ts?raw';
import solidjs187Types from '/node_modules/solidjs-use/dist/node_modules/@solidjs-use/shared/useToNumber/index.d.ts?raw';
import solidjs188Types from '/node_modules/solidjs-use/dist/node_modules/@solidjs-use/shared/useToString/index.d.ts?raw';
import solidjs189Types from '/node_modules/solidjs-use/dist/node_modules/@solidjs-use/shared/utils/filters.d.ts?raw';
import solidjs190Types from '/node_modules/solidjs-use/dist/node_modules/@solidjs-use/shared/utils/index.d.ts?raw';
import solidjs191Types from '/node_modules/solidjs-use/dist/node_modules/@solidjs-use/shared/utils/is.d.ts?raw';
import solidjs192Types from '/node_modules/solidjs-use/dist/node_modules/@solidjs-use/shared/utils/types.d.ts?raw';
import solidjs193Types from '/node_modules/solidjs-use/dist/node_modules/@solidjs-use/shared/watch/index.d.ts?raw';
import solidjs194Types from '/node_modules/solidjs-use/dist/node_modules/@solidjs-use/shared/watchArray/index.d.ts?raw';
import solidjs195Types from '/node_modules/solidjs-use/dist/node_modules/@solidjs-use/shared/watchAtMost/index.d.ts?raw';
import solidjs196Types from '/node_modules/solidjs-use/dist/node_modules/@solidjs-use/shared/watchDebounced/index.d.ts?raw';
import solidjs197Types from '/node_modules/solidjs-use/dist/node_modules/@solidjs-use/shared/watchIgnorable/index.d.ts?raw';
import solidjs198Types from '/node_modules/solidjs-use/dist/node_modules/@solidjs-use/shared/watchOnce/index.d.ts?raw';
import solidjs199Types from '/node_modules/solidjs-use/dist/node_modules/@solidjs-use/shared/watchPausable/index.d.ts?raw';
import solidjs200Types from '/node_modules/solidjs-use/dist/node_modules/@solidjs-use/shared/watchThrottled/index.d.ts?raw';
import solidjs201Types from '/node_modules/solidjs-use/dist/node_modules/@solidjs-use/shared/watchTriggerable/index.d.ts?raw';
import solidjs202Types from '/node_modules/solidjs-use/dist/node_modules/@solidjs-use/shared/watchWithFilter/index.d.ts?raw';
import solidjs203Types from '/node_modules/solidjs-use/dist/node_modules/@solidjs-use/shared/whenever/index.d.ts?raw';
import solidjs204Types from '/node_modules/solidjs-use/dist/node_modules/@solidjs-use/shared/node_modules/@solidjs-use/solid-to-vue/index.d.ts?raw';

function cmSolidjsUse(source: string, path: string) {
  languages.typescript.typescriptDefaults.addExtraLib(source, `file:///node_modules/solidjs-use/${path}`);
  languages.typescript.javascriptDefaults.addExtraLib(source, `file:///node_modules/solidjs-use/${path}`);
}

cmSolidjsUse(solidjsUsePackageJson, 'package.json');

cmSolidjsUse(solidjs1Types, 'dist/index.d.ts');
cmSolidjsUse(solidjs2Types, 'dist/solid-to-vue.d.ts');
cmSolidjsUse(solidjs3Types, 'dist/ssr-handlers.d.ts');
cmSolidjsUse(solidjs4Types, 'dist/types.d.ts');
cmSolidjsUse(solidjs5Types, 'dist/_configurable.d.ts');
cmSolidjsUse(solidjs6Types, 'dist/createAsyncMemo/index.d.ts');
cmSolidjsUse(solidjs7Types, 'dist/createUnAccessorFn/index.d.ts');
cmSolidjsUse(solidjs8Types, 'dist/onClickOutside/index.d.ts');
cmSolidjsUse(solidjs9Types, 'dist/onKeyStroke/index.d.ts');
cmSolidjsUse(solidjs10Types, 'dist/onLongPress/index.d.ts');
cmSolidjsUse(solidjs11Types, 'dist/onStartTyping/index.d.ts');
cmSolidjsUse(solidjs12Types, 'dist/useActiveElement/index.d.ts');
cmSolidjsUse(solidjs13Types, 'dist/useAsyncState/index.d.ts');
cmSolidjsUse(solidjs14Types, 'dist/useBase64/index.d.ts');
cmSolidjsUse(solidjs15Types, 'dist/useBase64/serialization.d.ts');
cmSolidjsUse(solidjs16Types, 'dist/useBattery/index.d.ts');
cmSolidjsUse(solidjs17Types, 'dist/useBluetooth/index.d.ts');
cmSolidjsUse(solidjs18Types, 'dist/useBreakpoints/breakpoints.d.ts');
cmSolidjsUse(solidjs19Types, 'dist/useBreakpoints/index.d.ts');
cmSolidjsUse(solidjs20Types, 'dist/useBroadcastChannel/index.d.ts');
cmSolidjsUse(solidjs21Types, 'dist/useBrowserLocation/component.d.ts');
cmSolidjsUse(solidjs22Types, 'dist/useBrowserLocation/index.d.ts');
cmSolidjsUse(solidjs23Types, 'dist/useClipboard/index.d.ts');
cmSolidjsUse(solidjs24Types, 'dist/useCloned/index.d.ts');
cmSolidjsUse(solidjs25Types, 'dist/useColorMode/index.d.ts');
cmSolidjsUse(solidjs26Types, 'dist/useConfirmDialog/index.d.ts');
cmSolidjsUse(solidjs27Types, 'dist/useCssTransition/index.d.ts');
cmSolidjsUse(solidjs28Types, 'dist/useCssVar/index.d.ts');
cmSolidjsUse(solidjs29Types, 'dist/useCycleList/index.d.ts');
cmSolidjsUse(solidjs30Types, 'dist/useDark/index.d.ts');
cmSolidjsUse(solidjs31Types, 'dist/useDebouncedHistoryTravel/index.d.ts');
cmSolidjsUse(solidjs32Types, 'dist/useDeviceMotion/index.d.ts');
cmSolidjsUse(solidjs33Types, 'dist/useDeviceOrientation/index.d.ts');
cmSolidjsUse(solidjs34Types, 'dist/useDevicePixelRatio/index.d.ts');
cmSolidjsUse(solidjs35Types, 'dist/useDevicesList/index.d.ts');
cmSolidjsUse(solidjs36Types, 'dist/useDisplayMedia/index.d.ts');
cmSolidjsUse(solidjs37Types, 'dist/useDocumentVisibility/index.d.ts');
cmSolidjsUse(solidjs38Types, 'dist/useDraggable/index.d.ts');
cmSolidjsUse(solidjs39Types, 'dist/useDropZone/index.d.ts');
cmSolidjsUse(solidjs40Types, 'dist/useElementBounding/index.d.ts');
cmSolidjsUse(solidjs41Types, 'dist/useElementByPoint/index.d.ts');
cmSolidjsUse(solidjs42Types, 'dist/useElementHover/index.d.ts');
cmSolidjsUse(solidjs43Types, 'dist/useElementSize/index.d.ts');
cmSolidjsUse(solidjs44Types, 'dist/useElementVisibility/index.d.ts');
cmSolidjsUse(solidjs45Types, 'dist/useEventBus/index.d.ts');
cmSolidjsUse(solidjs46Types, 'dist/useEventBus/internal.d.ts');
cmSolidjsUse(solidjs47Types, 'dist/useEventListener/index.d.ts');
cmSolidjsUse(solidjs48Types, 'dist/useEventSource/index.d.ts');
cmSolidjsUse(solidjs49Types, 'dist/useEyeDropper/index.d.ts');
cmSolidjsUse(solidjs50Types, 'dist/useFavicon/index.d.ts');
cmSolidjsUse(solidjs51Types, 'dist/useFetch/index.d.ts');
cmSolidjsUse(solidjs52Types, 'dist/useFileDialog/index.d.ts');
cmSolidjsUse(solidjs53Types, 'dist/useFileSystemAccess/index.d.ts');
cmSolidjsUse(solidjs54Types, 'dist/useFocus/index.d.ts');
cmSolidjsUse(solidjs55Types, 'dist/useFocusWithin/index.d.ts');
cmSolidjsUse(solidjs56Types, 'dist/useFps/index.d.ts');
cmSolidjsUse(solidjs57Types, 'dist/useFullscreen/index.d.ts');
cmSolidjsUse(solidjs58Types, 'dist/useGamepad/index.d.ts');
cmSolidjsUse(solidjs59Types, 'dist/useGeolocation/index.d.ts');
cmSolidjsUse(solidjs60Types, 'dist/useHistoryTravel/index.d.ts');
cmSolidjsUse(solidjs61Types, 'dist/useIdle/index.d.ts');
cmSolidjsUse(solidjs62Types, 'dist/useImage/index.d.ts');
cmSolidjsUse(solidjs63Types, 'dist/useInfiniteScroll/index.d.ts');
cmSolidjsUse(solidjs64Types, 'dist/useIntersectionObserver/index.d.ts');
cmSolidjsUse(solidjs65Types, 'dist/useKeyModifier/index.d.ts');
cmSolidjsUse(solidjs66Types, 'dist/useLocalStorage/index.d.ts');
cmSolidjsUse(solidjs67Types, 'dist/useMagicKeys/aliasMap.d.ts');
cmSolidjsUse(solidjs68Types, 'dist/useMagicKeys/index.d.ts');
cmSolidjsUse(solidjs69Types, 'dist/useManualHistoryTravel/index.d.ts');
cmSolidjsUse(solidjs70Types, 'dist/useMediaControls/index.d.ts');
cmSolidjsUse(solidjs71Types, 'dist/useMediaQuery/index.d.ts');
cmSolidjsUse(solidjs72Types, 'dist/useMemoize/index.d.ts');
cmSolidjsUse(solidjs73Types, 'dist/useMemory/index.d.ts');
cmSolidjsUse(solidjs74Types, 'dist/useMounted/index.d.ts');
cmSolidjsUse(solidjs75Types, 'dist/useMouse/index.d.ts');
cmSolidjsUse(solidjs76Types, 'dist/useMouseInElement/index.d.ts');
cmSolidjsUse(solidjs77Types, 'dist/useMousePressed/index.d.ts');
cmSolidjsUse(solidjs78Types, 'dist/useMutationObserver/index.d.ts');
cmSolidjsUse(solidjs79Types, 'dist/useNavigatorLanguage/index.d.ts');
cmSolidjsUse(solidjs80Types, 'dist/useNetwork/index.d.ts');
cmSolidjsUse(solidjs81Types, 'dist/useNow/component.d.ts');
cmSolidjsUse(solidjs82Types, 'dist/useNow/index.d.ts');
cmSolidjsUse(solidjs83Types, 'dist/useObjectUrl/component.d.ts');
cmSolidjsUse(solidjs84Types, 'dist/useObjectUrl/index.d.ts');
cmSolidjsUse(solidjs85Types, 'dist/useOffsetPagination/index.d.ts');
cmSolidjsUse(solidjs86Types, 'dist/useOnline/index.d.ts');
cmSolidjsUse(solidjs87Types, 'dist/usePageLeave/index.d.ts');
cmSolidjsUse(solidjs88Types, 'dist/useParallax/index.d.ts');
cmSolidjsUse(solidjs89Types, 'dist/usePermission/index.d.ts');
cmSolidjsUse(solidjs90Types, 'dist/usePointer/index.d.ts');
cmSolidjsUse(solidjs91Types, 'dist/usePointerSwipe/index.d.ts');
cmSolidjsUse(solidjs92Types, 'dist/usePreferredColorScheme/index.d.ts');
cmSolidjsUse(solidjs93Types, 'dist/usePreferredContrast/index.d.ts');
cmSolidjsUse(solidjs94Types, 'dist/usePreferredDark/component.d.ts');
cmSolidjsUse(solidjs95Types, 'dist/usePreferredDark/index.d.ts');
cmSolidjsUse(solidjs96Types, 'dist/usePreferredLanguages/index.d.ts');
cmSolidjsUse(solidjs97Types, 'dist/usePreferredReducedMotion/index.d.ts');
cmSolidjsUse(solidjs98Types, 'dist/useRafFn/index.d.ts');
cmSolidjsUse(solidjs99Types, 'dist/useResizeObserver/index.d.ts');
cmSolidjsUse(solidjs100Types, 'dist/useScreenOrientation/index.d.ts');
cmSolidjsUse(solidjs101Types, 'dist/useScreenSafeArea/index.d.ts');
cmSolidjsUse(solidjs102Types, 'dist/useScriptTag/index.d.ts');
cmSolidjsUse(solidjs103Types, 'dist/useScroll/index.d.ts');
cmSolidjsUse(solidjs104Types, 'dist/useScrollLock/index.d.ts');
cmSolidjsUse(solidjs105Types, 'dist/useSessionStorage/index.d.ts');
cmSolidjsUse(solidjs106Types, 'dist/useShare/index.d.ts');
cmSolidjsUse(solidjs107Types, 'dist/useSpeechRecognition/index.d.ts');
cmSolidjsUse(solidjs108Types, 'dist/useSpeechRecognition/types.d.ts');
cmSolidjsUse(solidjs109Types, 'dist/useSpeechSynthesis/index.d.ts');
cmSolidjsUse(solidjs110Types, 'dist/useStepper/index.d.ts');
cmSolidjsUse(solidjs111Types, 'dist/useStorage/guess.d.ts');
cmSolidjsUse(solidjs112Types, 'dist/useStorage/index.d.ts');
cmSolidjsUse(solidjs113Types, 'dist/useStorageAsync/index.d.ts');
cmSolidjsUse(solidjs114Types, 'dist/useStyleTag/index.d.ts');
cmSolidjsUse(solidjs115Types, 'dist/useSupported/index.d.ts');
cmSolidjsUse(solidjs116Types, 'dist/useSwipe/index.d.ts');
cmSolidjsUse(solidjs117Types, 'dist/useTextareaAutoSize/index.d.ts');
cmSolidjsUse(solidjs118Types, 'dist/useTextDirection/index.d.ts');
cmSolidjsUse(solidjs119Types, 'dist/useTextSelection/index.d.ts');
cmSolidjsUse(solidjs120Types, 'dist/useThrottledHistoryTravel/index.d.ts');
cmSolidjsUse(solidjs121Types, 'dist/useTimeAgo/component.d.ts');
cmSolidjsUse(solidjs122Types, 'dist/useTimeAgo/index.d.ts');
cmSolidjsUse(solidjs123Types, 'dist/useTimestamp/index.d.ts');
cmSolidjsUse(solidjs124Types, 'dist/useTitle/index.d.ts');
cmSolidjsUse(solidjs125Types, 'dist/useUrlSearchParams/index.d.ts');
cmSolidjsUse(solidjs126Types, 'dist/useUserMedia/index.d.ts');
cmSolidjsUse(solidjs127Types, 'dist/useVibrate/index.d.ts');
cmSolidjsUse(solidjs128Types, 'dist/useVirtualList/index.d.ts');
cmSolidjsUse(solidjs129Types, 'dist/useWakeLock/index.d.ts');
cmSolidjsUse(solidjs130Types, 'dist/useWebNotification/index.d.ts');
cmSolidjsUse(solidjs131Types, 'dist/useWebSocket/index.d.ts');
cmSolidjsUse(solidjs132Types, 'dist/useWebWorker/index.d.ts');
cmSolidjsUse(solidjs133Types, 'dist/useWebWorkerFn/index.d.ts');
cmSolidjsUse(solidjs134Types, 'dist/useWindowFocus/index.d.ts');
cmSolidjsUse(solidjs135Types, 'dist/useWindowScroll/index.d.ts');
cmSolidjsUse(solidjs136Types, 'dist/useWindowSize/index.d.ts');
cmSolidjsUse(solidjs137Types, 'dist/useWebWorkerFn/lib/createWorkerBlobUrl.d.ts');
cmSolidjsUse(solidjs138Types, 'dist/useWebWorkerFn/lib/depsParser.d.ts');
cmSolidjsUse(solidjs139Types, 'dist/useWebWorkerFn/lib/jobRunner.d.ts');
cmSolidjsUse(solidjs140Types, 'dist/node_modules/@solidjs-use/shared/index.d.ts');
cmSolidjsUse(solidjs141Types, 'dist/node_modules/@solidjs-use/shared/solid-to-vue.d.ts');
cmSolidjsUse(solidjs142Types, 'dist/node_modules/@solidjs-use/shared/accessorDebounced/index.d.ts');
cmSolidjsUse(solidjs143Types, 'dist/node_modules/@solidjs-use/shared/accessorDefault/index.d.ts');
cmSolidjsUse(solidjs144Types, 'dist/node_modules/@solidjs-use/shared/accessorThrottled/index.d.ts');
cmSolidjsUse(solidjs145Types, 'dist/node_modules/@solidjs-use/shared/createEventHook/index.d.ts');
cmSolidjsUse(solidjs146Types, 'dist/node_modules/@solidjs-use/shared/createSharedComposable/index.d.ts');
cmSolidjsUse(solidjs147Types, 'dist/node_modules/@solidjs-use/shared/get/index.d.ts');
cmSolidjsUse(solidjs148Types, 'dist/node_modules/@solidjs-use/shared/isDefined/index.d.ts');
cmSolidjsUse(solidjs149Types, 'dist/node_modules/@solidjs-use/shared/makeDestructurable/index.d.ts');
cmSolidjsUse(solidjs150Types, 'dist/node_modules/@solidjs-use/shared/mutableMemo/index.d.ts');
cmSolidjsUse(solidjs151Types, 'dist/node_modules/@solidjs-use/shared/omitMutable/index.d.ts');
cmSolidjsUse(solidjs152Types, 'dist/node_modules/@solidjs-use/shared/pickMutable/index.d.ts');
cmSolidjsUse(solidjs153Types, 'dist/node_modules/@solidjs-use/shared/reactify/index.d.ts');
cmSolidjsUse(solidjs154Types, 'dist/node_modules/@solidjs-use/shared/reactifyObject/index.d.ts');
cmSolidjsUse(solidjs155Types, 'dist/node_modules/@solidjs-use/shared/resolveAccessor/index.d.ts');
cmSolidjsUse(solidjs156Types, 'dist/node_modules/@solidjs-use/shared/signalAutoReset/index.d.ts');
cmSolidjsUse(solidjs157Types, 'dist/node_modules/@solidjs-use/shared/syncSignal/index.d.ts');
cmSolidjsUse(solidjs158Types, 'dist/node_modules/@solidjs-use/shared/syncSignals/index.d.ts');
cmSolidjsUse(solidjs159Types, 'dist/node_modules/@solidjs-use/shared/toAccessors/index.d.ts');
cmSolidjsUse(solidjs160Types, 'dist/node_modules/@solidjs-use/shared/toReactive/index.d.ts');
cmSolidjsUse(solidjs161Types, 'dist/node_modules/@solidjs-use/shared/tryOnCleanup/index.d.ts');
cmSolidjsUse(solidjs162Types, 'dist/node_modules/@solidjs-use/shared/tryOnMount/index.d.ts');
cmSolidjsUse(solidjs163Types, 'dist/node_modules/@solidjs-use/shared/unAccessor/index.d.ts');
cmSolidjsUse(solidjs164Types, 'dist/node_modules/@solidjs-use/shared/until/index.d.ts');
cmSolidjsUse(solidjs165Types, 'dist/node_modules/@solidjs-use/shared/useArrayEvery/index.d.ts');
cmSolidjsUse(solidjs166Types, 'dist/node_modules/@solidjs-use/shared/useArrayFilter/index.d.ts');
cmSolidjsUse(solidjs167Types, 'dist/node_modules/@solidjs-use/shared/useArrayFind/index.d.ts');
cmSolidjsUse(solidjs168Types, 'dist/node_modules/@solidjs-use/shared/useArrayFindIndex/index.d.ts');
cmSolidjsUse(solidjs169Types, 'dist/node_modules/@solidjs-use/shared/useArrayJoin/index.d.ts');
cmSolidjsUse(solidjs170Types, 'dist/node_modules/@solidjs-use/shared/useArrayMap/index.d.ts');
cmSolidjsUse(solidjs171Types, 'dist/node_modules/@solidjs-use/shared/useArrayReduce/index.d.ts');
cmSolidjsUse(solidjs172Types, 'dist/node_modules/@solidjs-use/shared/useArraySome/index.d.ts');
cmSolidjsUse(solidjs173Types, 'dist/node_modules/@solidjs-use/shared/useArrayUnique/index.d.ts');
cmSolidjsUse(solidjs174Types, 'dist/node_modules/@solidjs-use/shared/useAsyncQueue/index.d.ts');
cmSolidjsUse(solidjs175Types, 'dist/node_modules/@solidjs-use/shared/useCounter/index.d.ts');
cmSolidjsUse(solidjs176Types, 'dist/node_modules/@solidjs-use/shared/useDateFormat/index.d.ts');
cmSolidjsUse(solidjs177Types, 'dist/node_modules/@solidjs-use/shared/useDebounceFn/index.d.ts');
cmSolidjsUse(solidjs178Types, 'dist/node_modules/@solidjs-use/shared/useInterval/index.d.ts');
cmSolidjsUse(solidjs179Types, 'dist/node_modules/@solidjs-use/shared/useIntervalFn/index.d.ts');
cmSolidjsUse(solidjs180Types, 'dist/node_modules/@solidjs-use/shared/useLastChanged/index.d.ts');
cmSolidjsUse(solidjs181Types, 'dist/node_modules/@solidjs-use/shared/useSorted/index.d.ts');
cmSolidjsUse(solidjs182Types, 'dist/node_modules/@solidjs-use/shared/useThrottleFn/index.d.ts');
cmSolidjsUse(solidjs183Types, 'dist/node_modules/@solidjs-use/shared/useTimeout/index.d.ts');
cmSolidjsUse(solidjs184Types, 'dist/node_modules/@solidjs-use/shared/useTimeoutFn/index.d.ts');
cmSolidjsUse(solidjs185Types, 'dist/node_modules/@solidjs-use/shared/useTimeoutPoll/index.d.ts');
cmSolidjsUse(solidjs186Types, 'dist/node_modules/@solidjs-use/shared/useToggle/index.d.ts');
cmSolidjsUse(solidjs187Types, 'dist/node_modules/@solidjs-use/shared/useToNumber/index.d.ts');
cmSolidjsUse(solidjs188Types, 'dist/node_modules/@solidjs-use/shared/useToString/index.d.ts');
cmSolidjsUse(solidjs189Types, 'dist/node_modules/@solidjs-use/shared/utils/filters.d.ts');
cmSolidjsUse(solidjs190Types, 'dist/node_modules/@solidjs-use/shared/utils/index.d.ts');
cmSolidjsUse(solidjs191Types, 'dist/node_modules/@solidjs-use/shared/utils/is.d.ts');
cmSolidjsUse(solidjs192Types, 'dist/node_modules/@solidjs-use/shared/utils/types.d.ts');
cmSolidjsUse(solidjs193Types, 'dist/node_modules/@solidjs-use/shared/watch/index.d.ts');
cmSolidjsUse(solidjs194Types, 'dist/node_modules/@solidjs-use/shared/watchArray/index.d.ts');
cmSolidjsUse(solidjs195Types, 'dist/node_modules/@solidjs-use/shared/watchAtMost/index.d.ts');
cmSolidjsUse(solidjs196Types, 'dist/node_modules/@solidjs-use/shared/watchDebounced/index.d.ts');
cmSolidjsUse(solidjs197Types, 'dist/node_modules/@solidjs-use/shared/watchIgnorable/index.d.ts');
cmSolidjsUse(solidjs198Types, 'dist/node_modules/@solidjs-use/shared/watchOnce/index.d.ts');
cmSolidjsUse(solidjs199Types, 'dist/node_modules/@solidjs-use/shared/watchPausable/index.d.ts');
cmSolidjsUse(solidjs200Types, 'dist/node_modules/@solidjs-use/shared/watchThrottled/index.d.ts');
cmSolidjsUse(solidjs201Types, 'dist/node_modules/@solidjs-use/shared/watchTriggerable/index.d.ts');
cmSolidjsUse(solidjs202Types, 'dist/node_modules/@solidjs-use/shared/watchWithFilter/index.d.ts');
cmSolidjsUse(solidjs203Types, 'dist/node_modules/@solidjs-use/shared/whenever/index.d.ts');
cmSolidjsUse(solidjs204Types, 'dist/node_modules/@solidjs-use/shared/node_modules/@solidjs-use/solid-to-vue/index.d.ts');
